{
	"version": 1650570445,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/arkaplan.png",
		"images/sorusprt-sheet0.png",
		"images/sorusprt-sheet1.png",
		"images/sorusprt-sheet2.png",
		"images/sorusprt-sheet3.png",
		"images/duyular-sheet0.png",
		"images/duyular-sheet1.png",
		"images/anasayfa-sheet0.png",
		"images/ses-sheet0.png",
		"images/ses-sheet1.png",
		"images/ilerisprt-sheet0.png",
		"images/yapbozsprt-sheet0.png",
		"images/yapbozsprt-sheet1.png",
		"images/oyunhakkinda-sheet0.png",
		"images/oyunabasla-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground2.png",
		"images/girisarka-sheet0.png",
		"images/yapbozsprt2-sheet0.png",
		"images/logo-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite2-sheet0.png",
		"images/kelebekspt-sheet0.png",
		"images/kelebekspt-sheet1.png",
		"images/dugru_yanlis-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/notasprt-sheet0.png",
		"images/balonsprt-sheet0.png",
		"images/balonsprt-sheet1.png",
		"media/bitiş.m4a",
		"media/bitiş.ogg",
		"media/buton.m4a",
		"media/buton.ogg",
		"media/doğru.m4a",
		"media/doğru.ogg",
		"media/fen bi̇li̇mleri̇ jeneri̇k.m4a",
		"media/fen bi̇li̇mleri̇ jeneri̇k.ogg",
		"media/fen müzik.m4a",
		"media/fen müzik.ogg",
		"media/yanliş.m4a",
		"media/yanliş.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}